name: Simple Composer Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate Project 1
      run: composer validate
      working-directory: project1

    - name: Validate Project 2
      run: composer validate
      working-directory: project2

    - name: Validate Project 3
      run: composer validate
      working-directory: project3

    - name: Validate Project 4
      run: composer validate
      working-directory: project4      

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
